apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-server
  labels:
    app: {{ template "fullname" . }}-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-server
    spec:
      containers:
      - name: {{ template "fullname" . }}-server
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.server.resources | indent 10 }}
        env:
        - name: DRONE_OPEN
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: gitlab_omnibus_config

        {{- if .Values.factorioServer.password }}
        - name: FACTORIO_GAME_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: server-password
        {{- end }}

        {{- if .Values.factorioServer.isPublic }}
        - name: FACTORIO_USER_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: factorio-username
        - name: FACTORIO_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: factorio-password
        {{- end }}

        {{- if .Values.factorioServer.rcon.enabled }}
        - name: FACTORIO_RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: rcon-password
        {{- end }}

        ports:
        - name: factorio
          containerPort: 34197
          protocol: UDP
        {{- if .Values.factorioServer.rcon.enabled }}
        - name: rcon
          containerPort: {{ .Values.factorioServer.rcon.port }}
          protocol: TCP
        {{- end}}
        volumeMounts:
        - name: saves
          mountPath: /opt/factorio/saves
        - name: mods
          mountPath: /opt/factorio/mods
      volumes:
      - name: saves
      {{- if .Values.persistence.savedGames.enabled }}
        persistentVolumeClaim:
          claimName: {{template "fullname" .}}-savedgames
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: mods
      {{- if .Values.persistence.mods.enabled }}
        persistentVolumeClaim:
          claimName: {{template "fullname" .}}-mods
      {{- else }}
        emptyDir: {}
      {{- end }}
